@host = http://localhost:5214
POST {{host}}/api/Subscription
Content-Type: application/json

{
  "SubscriptionType": "Free",
  "AdminId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

###
@SubscriptionId=523d5419-02f1-4c94-835c-3c1409927c46
Get {{host}}/api/Subscription/{{SubscriptionId}}